# basic innstillinger
# _config.yml
title: "SuperDiplomatarium"
description: "..."
url: "https://moryzont.github.io"     # no trailing slash
baseurl: "/SuperDiplomatarium"         # LEADING slash, NO trailing slash


# Build settings
markdown: kramdown
encoding: utf-8

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - "*.csv"
  
# Collections (optional for now)
collections:
  letters:
    output: false