# basic innstillinger
title: Diplomatariumet i ny form
description: Digital samling av 19.000 brev fra norsk og skandinavisk middelalder
baseurl: ""
url: ""

# Build settings
markdown: kramdown
encoding: utf-8

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - "*.csv"
  
# Collections (optional for now)
collections:
  letters:
    output: false